[package]
name = "rust-os"
version = "0.1.0"
authors = ["Seth <swidoff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Disable stack unwinding which requires OS specific libraries.

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"